#!/usr/bin/env ruby

require 'rake'
require 'daemons'

#
# script to run the Que workers in background processes
# easily manageable using startstop/restart commands
#

current_dir = Dir.pwd
options = {}
options = { dir_mode: :normal, dir: ARGV[1] } if ARGV.size > 1
Daemons.run_proc(File.basename(__FILE__), options) do
  Dir.chdir(current_dir)
  Rake.application.init
  Rake.application.load_rakefile
  Rake::Task['que:work'].invoke
end
